
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        stages: [manual, commit]
      - id: check-merge-conflict
        stages: [manual, commit]
      - id: end-of-file-fixer
        stages: [manual, commit]
      - id: requirements-txt-fixer
        stages: [manual, commit]
      - id: trailing-whitespace
        stages: [manual, commit]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        stages: [manual, commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        additional_dependencies: [types-all]
        stages: [manual, push]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-lock
        stages: [manual, push]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: ["--fix"]
        stages: [manual, push]
